import {
	UText,
	UTitle
} from "@sleek-ui/widgets.slint";
import { UAppTheme } from "@sleek-ui/app-theme.slint";
import { ScrollView, AboutSlint } from "std-widgets.slint";


export component About {
    ScrollView {
        VerticalLayout {
            padding: 10px * UAppTheme.scale-factor;
            HorizontalLayout {
                alignment: start;
                padding-bottom: 36px * UAppTheme.scale-factor;
                UTitle {
                    level: 4;
                    text: "About";
                }
            }

            UText {
                wrap: word-wrap;
                text: "This is a controller GUI for the TCN Artekmed Holoscan Applciation.";
            }

            Rectangle { }

            HorizontalLayout {
                alignment: center;
                AboutSlint {
                    width: 175px * UAppTheme.scale-factor;
                }
            }
        }
    }
}