// import "./assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf";
// import "./assets/fonts/Inter-VariableFont_opsz,wght.ttf";

import { UAppTheme } from "@sleek-ui/app-theme.slint";
import { UText } from "@sleek-ui/widgets.slint";
import { Sidebar, SidebarLogic } from "components/sidebar.slint";
import { About } from "pages/about.slint";
import { OptionsBar, OptionsBarLogic } from "components/options-bar.slint";

import { RpcClient, Parameter, ParameterSchema } from "components/rpc-client.slint";
import { ParameterEditor } from "pages/parameter-editor.slint";

export { UAppTheme, OptionsBarLogic, RpcClient }

export component AppWindow inherits Window {

    in-out property<[string]> sidebar-pages <=> sidebar.pages;

    title: "Artekmed Controller";
    default-font-family: "Inter";
    default-font-size: 14px;
    min-width: 800px * UAppTheme.scale-factor;
    min-height: 840px * UAppTheme.scale-factor;
    background: UAppTheme.bg-container;
    FocusScope {
        capture-key-pressed(event) => {
            reject
        }
    }

    VerticalLayout {
        OptionsBar { }

        HorizontalLayout {
            vertical-stretch: 1;
            sidebar := Sidebar {
                height: 100%;
            }

//            if SidebarLogic.current-page == "Controls": Controls {
//                horizontal-stretch: 1;
//            }
//            if SidebarLogic.current-page == "Data display": DataDisplay {
//                horizontal-stretch: 1;
//            }
//            if SidebarLogic.current-page == "Feedback": Feedback {
//                horizontal-stretch: 1;
//                open-modal => {
//                    modal.show();
//                }
//            }
//            if SidebarLogic.current-page == "Navigation": Navigation {
//                horizontal-stretch: 1;
//            }
            ParameterEditor {
                component-name: SidebarLogic.current-page;
            }
        }
    }
}
