import { Palette } from "std-widgets.slint";

import {
    UDivider,
    USelect,
    USelectOption,
    UText,
    USwitch,
} from "@sleek-ui/widgets.slint";
import { UAppTheme } from "@sleek-ui/app-theme.slint";
import { UPrimaryColors } from "@sleek-ui/styling/colors.slint";
import { UColorSchemeVariantsColor } from "@sleek-ui/structs/colors.slint";


export global OptionsBarLogic {
    in-out property <bool> widgets-enabled: true;
}

export component OptionsBar inherits Rectangle {
    VerticalLayout {
        HorizontalLayout {
            alignment: space-between;
            padding: UAppTheme.padding-base;
            HorizontalLayout {
                alignment: start;
                spacing: UAppTheme.spacing-base;
                USelect {
                    private property <[USelectOption]> color-scheme-options: [
                        { text: "Light", value: "light", enabled: true },
                        { text: "Dark", value: "dark", enabled: true },
                        { text: "System", value: "system", enabled: true }
                    ];
                    width: 95px * UAppTheme.scale-factor;
                    current-index: 2;
                    options: color-scheme-options;
                    selected-changed(_) => {
                        if self.selected-value == "light" {
                            Palette.color-scheme = ColorScheme.light;
                        } else if self.selected-value == "dark" {
                            Palette.color-scheme = ColorScheme.dark;
                        }
                    }
                }

            }

            HorizontalLayout {
                spacing: UAppTheme.spacing-base;
                VerticalLayout {
                    alignment: center;
                    UText {
                        text: "Widgets enabled:";
                    }
                }

                VerticalLayout {
                    alignment: center;
                    USwitch {
                        checked <=> OptionsBarLogic.widgets-enabled;
                    }
                }
            }
        }

        UDivider {
            width: 100%;
        }
    }
}
